import { api } from '../lib/utils/api';
import { buildQueryString } from '../lib/utils/queryParams';

export const guias = {
  list:   (params = { limit: 15 }) => api.get(`/guias-remision/${buildQueryString(params)}`),
  get:    (id)          => api.get(`/guias-remision/${id}`),
  create: (data)        => api.post('/guias-remision/', data),
  documentContext: (id, dispatchId = null) => api.get(`/facturacion/comprobantes/${id}/despacho-contexto${dispatchId ? `?dispatch_id=${dispatchId}` : ''}`),
  documentGuides: (id)  => api.get(`/facturacion/comprobantes/${id}/guias`),
  reconcileHistoricalDocument: (id, data) => api.post(`/facturacion/comprobantes/${id}/conciliar-despacho-historico`, data),
  invoiceContext: (id, dispatchId = null) => api.get(`/facturacion/facturas/${id}/despacho-contexto${dispatchId ? `?dispatch_id=${dispatchId}` : ''}`),
  invoiceGuides: (id)   => api.get(`/facturacion/facturas/${id}/guias`),
  reconcileHistoricalInvoice: (id, data) => api.post(`/facturacion/facturas/${id}/conciliar-despacho-historico`, data),
  dispatch: (id)        => api.get(`/despachos/${id}`),
  createFromInvoice: (data) => api.post('/guias-remision/desde-factura', data),
  createFromDocument: (data) => api.post('/guias-remision/desde-comprobante', data),
  createTransport: (data) => api.post('/guias-remision/transportista', data),
  updateDispatch: (guideId, data) => api.put(`/guias-remision/${guideId}`, data),
  cancelDraft: (guideId) => api.post(`/guias-remision/${guideId}/cancelar-borrador`, {}),
  validate: (guideId)   => api.post(`/guias-remision/${guideId}/validar`, {}),
  reconcile: (guideId)  => api.post(`/guias-remision/${guideId}/consultar`, {}),
  confirmDeparture: (dispatchId, idempotencyKey) => api.post(`/despachos/${dispatchId}/confirmar-salida`, { idempotency_key: idempotencyKey }),
  registerExternalCarrier: (guideId, guide) => api.post(`/guias-remision/${guideId}/gre-transportista-externa`, { guide }),
  verifyExternalReference: (guideId, data) => api.post(`/guias-remision/${guideId}/verificar-referencia-externa`, data),
  salesDocuments: (params = {}) => api.get(`/facturas-emitidas/page${buildQueryString({ tab: 'all', limit: 15, ...params })}`),
  invoices: () => api.get('/facturas-emitidas/page?tipo_comprobante=01&tab=emitted&limit=100'),
  emitir: (id)          => api.post(`/guias-remision/${id}/emitir?mode=async`, {}),
  getEmissionJob: (id)  => api.get(`/emission-jobs/${id}`),
  download: (id, type)  => api.download(`/guias-remision/${id}/${type}`),
};
