"""
models/__init__.py — Re-exporta todo el namespace de modelos de forma plana.

Importar todos los submódulos aquí garantiza que SQLAlchemy registre todas las
clases en el mapper registry antes de la primera consulta, resolviendo los
string-references en relationship("ClassName", ...).
"""

from database import Base
from models.access_requests import AccessRequest, ACCESS_REQUEST_PENDING, ACCESS_REQUEST_APPROVED, ACCESS_REQUEST_REJECTED

from models.tenants import (
    Tenant,
    User,
    AuditLog,
    Subscription,
    SubscriptionPayment,
    UsageLimit,
    SUBSCRIPTION_STATUS_ACTIVE,
    SUBSCRIPTION_STATUS_SUSPENDED,
    SUBSCRIPTION_STATUS_TRIAL,
    SUBSCRIPTION_STATUS_EXPIRED,
    SUBSCRIPTION_STATUS_CANCELLED,
    SMARTPSE_STATUS_OK,
    SMARTPSE_STATUS_INVALID,
    SMARTPSE_STATUS_UNCHECKED,
    SMARTPSE_GRE_STATUS_OK,
    SMARTPSE_GRE_STATUS_INVALID,
    SMARTPSE_GRE_STATUS_UNCHECKED,
    ONBOARDING_STATUS_NOT_STARTED,
    ONBOARDING_STATUS_IN_PROGRESS,
    ONBOARDING_STATUS_COMPLETED,
    USAGE_LIMIT_KIND_FACTURA,
    USAGE_LIMIT_KIND_BOLETA,
    USAGE_LIMIT_KIND_GUIA,
    USAGE_LIMIT_KIND_NOTA_CREDITO,
    USAGE_LIMIT_KIND_NOTA_DEBITO,
    USAGE_LIMIT_KINDS,
    USAGE_LIMIT_PERIOD_MONTH,
    USAGE_LIMIT_PERIOD_DAY,
    USAGE_LIMIT_PERIOD_TOTAL,
    USAGE_LIMIT_PERIODS,
)

from models.clientes import Cliente

from models.productos import Producto
from models.catalog import (
    TenantProductEntitlement,
    CatalogSite,
    CatalogAsset,
    CatalogCategory,
    CatalogItem,
    CatalogItemAsset,
    CatalogCollection,
    CatalogCollectionItem,
    CATALOG_PRODUCT_CODE,
    CATALOG_ENTITLEMENT_STATUSES,
    CATALOG_SITE_STATUSES,
    CATALOG_ITEM_KINDS,
    CATALOG_PRICE_MODES,
    CATALOG_PRICE_SOURCES,
    CATALOG_AVAILABILITY_SOURCES,
    CATALOG_AVAILABILITY_STATUSES,
)
from models.inventory import (
    TenantEstablishment,
    Warehouse,
    InventoryBalance,
    InventoryMovement,
    InventoryHold,
    InventoryTransfer,
    InventoryTransferItem,
    InternalTransferOrder,
    InternalTransferOrderLine,
    InternalTransferDispatch,
    InternalTransferDispatchLine,
    InternalTransferReceipt,
    InternalTransferReceiptLine,
    InventoryReturn,
    InventoryReturnItem,
)

from models.cotizaciones import Cotizacion, CotizacionItem

from models.guias import (
    GuiaRemision,
    GuiaRemisionItem,
    SaleDispatch,
    SaleDispatchLine,
    GuideExternalReference,
    DISPATCH_STATUS_PROVISIONAL,
    DISPATCH_STATUS_DRAFT,
    DISPATCH_STATUS_GUIDE_PENDING,
    DISPATCH_STATUS_GUIDE_ACCEPTED,
    DISPATCH_STATUS_GUIDE_REJECTED,
    DISPATCH_STATUS_DEPARTED,
    DISPATCH_STATUS_CANCELLED,
    DISPATCH_STATUS_BLOCKED,
    DISPATCH_RESERVATION_PROVISIONAL,
    DISPATCH_RESERVATION_ACTIVE,
    DISPATCH_RESERVATION_COVERED,
    DISPATCH_RESERVATION_RELEASED,
)

from models.pagos import Pago

from models.resumenes import (
    ResumenDiario,
    RESUMEN_DIARIO_STATUS_SENT,
    RESUMEN_DIARIO_STATUS_PENDING,
    RESUMEN_DIARIO_STATUS_REJECTED,
)
from models.reversiones import (
    ReversionFiscal,
    REVERSION_STATUS_SENT,
    REVERSION_STATUS_PENDING,
    REVERSION_STATUS_REJECTED,
)
from models.retenciones import (
    RetencionFiscal,
    RETENCION_STATUS_SENT,
    RETENCION_STATUS_PENDING,
    RETENCION_STATUS_REJECTED,
)
from models.percepciones import (
    PercepcionFiscal,
    PERCEPCION_STATUS_SENT,
    PERCEPCION_STATUS_PENDING,
    PERCEPCION_STATUS_REJECTED,
)

from models.frozen import (
    Insumo,
    RecetaBOM,
    Proveedor,
    OrdenProduccion,
    OrdenProduccionDetalle,
    AlertaInventario,
)
from models.emission_jobs import (
    DocumentEmissionJob,
    DocumentEmissionAttempt,
    EMISSION_JOB_STATUS_QUEUED,
    EMISSION_JOB_STATUS_PROCESSING,
    EMISSION_JOB_STATUS_RETRY,
    EMISSION_JOB_STATUS_PENDING_CONFIRMATION,
    EMISSION_JOB_STATUS_CONTINGENCY_PENDING,
    EMISSION_JOB_STATUS_SUCCEEDED,
    EMISSION_JOB_STATUS_FAILED,
    EMISSION_JOB_ACTION_EMIT_FISCAL,
    EMISSION_JOB_ACTION_EMIT_NOTE,
    EMISSION_JOB_ACTION_VOID_FISCAL,
    EMISSION_JOB_ACTION_EMIT_GUIDE,
    EMISSION_JOB_ACTION_CONSULT_GUIDE,
    EMISSION_JOB_RESOURCE_COTIZACION,
    EMISSION_JOB_RESOURCE_GUIA,
    EMISSION_ATTEMPT_STATUS_PROCESSING,
    EMISSION_ATTEMPT_STATUS_RETRY,
    EMISSION_ATTEMPT_STATUS_PENDING_CONFIRMATION,
    EMISSION_ATTEMPT_STATUS_SUCCEEDED,
    EMISSION_ATTEMPT_STATUS_FAILED,
)

__all__ = [
    "AccessRequest",
    "ACCESS_REQUEST_PENDING", "ACCESS_REQUEST_APPROVED", "ACCESS_REQUEST_REJECTED",
    "Base",
    # tenants
    "Tenant",
    "User",
    "AuditLog",
    "Subscription",
    "SubscriptionPayment",
    "SUBSCRIPTION_STATUS_ACTIVE",
    "SUBSCRIPTION_STATUS_SUSPENDED",
    "SUBSCRIPTION_STATUS_TRIAL",
    "SUBSCRIPTION_STATUS_EXPIRED",
    "SUBSCRIPTION_STATUS_CANCELLED",
    "SMARTPSE_STATUS_OK",
    "SMARTPSE_STATUS_INVALID",
    "SMARTPSE_STATUS_UNCHECKED",
    "SMARTPSE_GRE_STATUS_OK",
    "SMARTPSE_GRE_STATUS_INVALID",
    "SMARTPSE_GRE_STATUS_UNCHECKED",
    "ONBOARDING_STATUS_NOT_STARTED",
    "ONBOARDING_STATUS_IN_PROGRESS",
    "ONBOARDING_STATUS_COMPLETED",
    "UsageLimit",
    "USAGE_LIMIT_KIND_FACTURA",
    "USAGE_LIMIT_KIND_BOLETA",
    "USAGE_LIMIT_KIND_GUIA",
    "USAGE_LIMIT_KIND_NOTA_CREDITO",
    "USAGE_LIMIT_KIND_NOTA_DEBITO",
    "USAGE_LIMIT_KINDS",
    "USAGE_LIMIT_PERIOD_MONTH",
    "USAGE_LIMIT_PERIOD_DAY",
    "USAGE_LIMIT_PERIOD_TOTAL",
    "USAGE_LIMIT_PERIODS",
    # clientes
    "Cliente",
    # productos
    "Producto",
    "TenantProductEntitlement", "CatalogSite", "CatalogAsset", "CatalogCategory",
    "CatalogItem", "CatalogItemAsset", "CatalogCollection", "CatalogCollectionItem",
    "CATALOG_PRODUCT_CODE", "CATALOG_ENTITLEMENT_STATUSES", "CATALOG_SITE_STATUSES",
    "CATALOG_ITEM_KINDS", "CATALOG_PRICE_MODES", "CATALOG_PRICE_SOURCES",
    "CATALOG_AVAILABILITY_SOURCES", "CATALOG_AVAILABILITY_STATUSES",
    "TenantEstablishment", "Warehouse",
    "InventoryBalance",
    "InventoryMovement",
    "InventoryHold",
    "InventoryTransfer",
    "InventoryTransferItem",
    "InternalTransferOrder", "InternalTransferOrderLine",
    "InternalTransferDispatch", "InternalTransferDispatchLine",
    "InternalTransferReceipt", "InternalTransferReceiptLine",
    "InventoryReturn",
    "InventoryReturnItem",
    # cotizaciones
    "Cotizacion",
    "CotizacionItem",
    # guias
    "GuiaRemision",
    "GuiaRemisionItem",
    "SaleDispatch",
    "SaleDispatchLine",
    "GuideExternalReference",
    "DISPATCH_STATUS_PROVISIONAL",
    "DISPATCH_STATUS_DRAFT",
    "DISPATCH_STATUS_GUIDE_PENDING",
    "DISPATCH_STATUS_GUIDE_ACCEPTED",
    "DISPATCH_STATUS_GUIDE_REJECTED",
    "DISPATCH_STATUS_DEPARTED",
    "DISPATCH_STATUS_CANCELLED",
    "DISPATCH_STATUS_BLOCKED",
    "DISPATCH_RESERVATION_PROVISIONAL",
    "DISPATCH_RESERVATION_ACTIVE",
    "DISPATCH_RESERVATION_COVERED",
    "DISPATCH_RESERVATION_RELEASED",
    # pagos
    "Pago",
    "ResumenDiario",
    "RESUMEN_DIARIO_STATUS_SENT",
    "RESUMEN_DIARIO_STATUS_PENDING",
    "RESUMEN_DIARIO_STATUS_REJECTED",
    "ReversionFiscal",
    "REVERSION_STATUS_SENT",
    "REVERSION_STATUS_PENDING",
    "REVERSION_STATUS_REJECTED",
    "RetencionFiscal",
    "RETENCION_STATUS_SENT",
    "RETENCION_STATUS_PENDING",
    "RETENCION_STATUS_REJECTED",
    "PercepcionFiscal",
    "PERCEPCION_STATUS_SENT",
    "PERCEPCION_STATUS_PENDING",
    "PERCEPCION_STATUS_REJECTED",
    "DocumentEmissionJob",
    "DocumentEmissionAttempt",
    "EMISSION_JOB_STATUS_QUEUED",
    "EMISSION_JOB_STATUS_PROCESSING",
    "EMISSION_JOB_STATUS_RETRY",
    "EMISSION_JOB_STATUS_PENDING_CONFIRMATION",
    "EMISSION_JOB_STATUS_CONTINGENCY_PENDING",
    "EMISSION_JOB_STATUS_SUCCEEDED",
    "EMISSION_JOB_STATUS_FAILED",
    "EMISSION_JOB_ACTION_EMIT_FISCAL",
    "EMISSION_JOB_ACTION_EMIT_NOTE",
    "EMISSION_JOB_ACTION_VOID_FISCAL",
    "EMISSION_JOB_ACTION_EMIT_GUIDE",
    "EMISSION_JOB_ACTION_CONSULT_GUIDE",
    "EMISSION_JOB_RESOURCE_COTIZACION",
    "EMISSION_JOB_RESOURCE_GUIA",
    "EMISSION_ATTEMPT_STATUS_PROCESSING",
    "EMISSION_ATTEMPT_STATUS_RETRY",
    "EMISSION_ATTEMPT_STATUS_PENDING_CONFIRMATION",
    "EMISSION_ATTEMPT_STATUS_SUCCEEDED",
    "EMISSION_ATTEMPT_STATUS_FAILED",
    # frozen / MRP
    "Insumo",
    "RecetaBOM",
    "Proveedor",
    "OrdenProduccion",
    "OrdenProduccionDetalle",
    "AlertaInventario",
]
